// <auto-generated />
using System;
using ClientesCX_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientesCX_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200825000954_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("ClientesCX_WebAPI.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("dt_registro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            id = 1,
                            dt_registro = "242424",
                            email = "Rodrigues",
                            nome = "Renata",
                            telefone = "renata@cx.com.br"
                        },
                        new
                        {
                            id = 2,
                            dt_registro = "203030",
                            email = "Tavares",
                            nome = "Roger",
                            telefone = "rtavares@cx.com.br"
                        },
                        new
                        {
                            id = 3,
                            dt_registro = "949493",
                            email = "Lima",
                            nome = "Ricardo",
                            telefone = "lima@cx.com.br"
                        },
                        new
                        {
                            id = 4,
                            dt_registro = "202010",
                            email = "Diego",
                            nome = "Rayssa",
                            telefone = "rdiego@cx.com.br"
                        });
                });

            modelBuilder.Entity("ClientesCX_WebAPI.Models.Contatos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Clienteid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "renata@cx.com.br",
                            idCliente = 1,
                            nome = "Paula",
                            telefone = "242424"
                        },
                        new
                        {
                            id = 2,
                            email = "rtavares@cx.com.br",
                            idCliente = 2,
                            nome = "Laura",
                            telefone = "203030"
                        },
                        new
                        {
                            id = 3,
                            email = "lima@cx.com.br",
                            idCliente = 3,
                            nome = "Lima",
                            telefone = "949493"
                        },
                        new
                        {
                            id = 4,
                            email = "teste@cx.com.br",
                            idCliente = 4,
                            nome = "Teste",
                            telefone = "050504"
                        });
                });

            modelBuilder.Entity("ClientesCX_WebAPI.Models.Contatos", b =>
                {
                    b.HasOne("ClientesCX_WebAPI.Models.Cliente", "Cliente")
                        .WithMany("Contatos")
                        .HasForeignKey("Clienteid");
                });
#pragma warning restore 612, 618
        }
    }
}
